# indicating which version of Docker-compose we wish to use
version: "3"

# we will be creating these services
services:
  flask:
    # Note that we are building from our current terminal directory where our Dockerfile is located, we use .
    build: ./flask_app
    # naming our resulting container
    container_name: flask
    # publishing a port so that external services requesting port 8000 on your local machine
    # are mapped to port 8000 on our container
    ports:
      - "5000:5000"
    restart:
      on-failure

  nginx: 
    # Since our Dockerfile for web-server is located in react-app foler, our build context is ./react-app
    build: ./react_app
    container_name: nginx
    ports:
      - "3000:3000"
    # Networks
    restart:
      on-failure
