version: "3"

services:
  flask:
    build: ./flask_app
    container_name: flask
    ports:
      - "5000:5000"
    restart:
      on-failure

  nginx: 
    build: ./react_app
    container_name: nginx
    ports:
      - "3000:3000"
    restart:
      on-failure
